# docker compose for dev
services:
  web:
    build: .
    # container_name: django_app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0 # force redus_url to be using redis hostname with redis service name
      - DB_HOST=db # force to be using db_host with db service name
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: ["python", "manage.py", "runserver", "0.0.0.0:3001"]
    env_file:
      - .env
