# docker compose for dev
services:
  web:
    build: .
    container_name: django_app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: ["python", "manage.py", "runserver", "0.0.0.0:3001"]
    env_file:
      - .env
